# Generated by Django 5.1.7 on 2025-03-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='born_year',
            new_name='date_born',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='release_year',
            new_name='release_date',
        ),
    ]
