# Generated by Django 5.1.7 on 2025-03-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_born_year_author_date_born_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
